title: Competitive Programming Primer
description: A repository of competitive programming problems and resources

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light
search_enabled: true
nav_enabled: true

logo: "/assets/images/logo.png"